name: dart_dice_parser
description: A dart library for parsing dice notation (like "2d6+4", "3d6", or "3d10 + 2d6 - 5d4")
version: 1.1.1
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  petitparser: ^2.3.0
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.6.3
  mockito: ^3.0.2
  args: ^1.5.2
