name: dart_dice_parser
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/stevesea/dart-dice-parser
author: steve christensen <adventuresmith_rpg@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  petitparser: 1.6.1
  args: "^1.1.0"

dev_dependencies:
  test: ^0.12.0
  mockito: 2.2.0
