name: dart_dice_parser
description: A dart library for parsing dice notation (e.g. "2d6+4"). Supports advantage/disadvantage, exploding die, and other variations.
version: 5.1.4
homepage: https://github.com/Adventuresmith/dart-dice-parser
repository: https://github.com/Adventuresmith/dart-dice-parser

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  logging: ^1.1.0
  meta: ^1.8.0
  petitparser: ^5.0.0

dev_dependencies:
  args: ^2.3.1
  lint: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.21.6
