name: dart_dice_parser
description: A dart library for parsing dice notation (like "2d6+4", "3d6", or "3d10 + 2d6 - 5d4")
version: 1.3.2
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  petitparser: ^2.3.0
  logging: ^0.11.3+2
  stats: ^0.2.0+2

dev_dependencies:
  test: ^1.6.4
  mockito: ^4.1.0
  args: ^1.5.2
