name: dart_dice_parser
description: A dart library for parsing dice notation (e.g. "2d6+4"). Supports advantage/disadvantage, exploding die, and other variations.
version: 6.0.3
homepage: https://github.com/Adventuresmith/dart-dice-parser
repository: https://github.com/Adventuresmith/dart-dice-parser

environment:
  sdk: '^3.5.0'

dependencies:
  collection: ^1.0.0
  equatable: ^2.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  petitparser: ^6.0.0

dev_dependencies:
  args: ^2.0.0
  lint: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.0.0
