name: dart_dice_parser
description: A small library for parsing dice notation
version: 0.2.0
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  petitparser: ^2.0.2

dev_dependencies:
  test: ^1.3.4
  mockito: ^3.0.0
  args: ^1.5.0
