name: dart_dice_parser
description: A small library for parsing dice notation
version: 0.0.3
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  petitparser: ^1.6.1
  args: ">=0.13.4 <2.0.0"

dev_dependencies:
  test: ^0.12.0
  mockito: 2.2.0
