name: dart_dice_parser
description: A dart library for parsing dice notation (like "2d6+4", "3d6", or "3d10 + 2d6 - 5d4")
version: 2.0.1
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  petitparser: ^2.4.0
  logging: ^0.11.4

dev_dependencies:
  test: ^1.12.0
  mockito: ^4.1.1
  args: ^1.5.2
