name: dart_dice_parser
description: A dart library for parsing dice notation (like "2d6+4", "3d6", or "3d10 + 2d6 - 5d4")
version: 3.0.0
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  petitparser: ^5.0.0

dev_dependencies:
  test: ^1.21.6
  mockito: ^5.3.2
  args: ^2.3.1
