name: dart_dice_parser
description: A small library for parsing dice notation
version: 0.0.2
homepage: https://github.com/stevesea/dart-dice-parser
authors:
  - steve christensen <adventuresmith_rpg@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  petitparser: ^1.6.1

dev_dependencies:
  test: ^0.12.0
  mockito: 2.2.0
  args: ^1.1.0
