# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  deps:
    docker:
      - image: dart:stable
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: dart pub get
      - save_cache:
          paths:
            - pubspec.lock
            - .packages
            - .dart_tool
            - ~/.pub-cache
          key: v2-pubcache-{{ checksum "pubspec.yaml" }}

  test:
    docker:
      - image: dart:stable
    steps:
      - checkout
      - restore_cache:
          key: v2-pubcache-{{ checksum "pubspec.yaml" }}
      - run:
          name: Lint
          command: bash -c '[[ "$(dartfmt -n . | wc -l)" -eq "0" ]]'
      - run:
          name: Dartanalyze
          command: dart analyze  --fatal-warnings . # --fatal-infos
      - run:
          name: Test
          command: dart pub run test

workflows:
  version: 2
  build:
    jobs:
      - deps
      - test:
          requires:
            - deps
